# Save as .codeclimate.yml (note leading .) in project root directory
plugins:
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - ".github/**/*"
  - "docs/**/*"
  - "sami2py/tests/**/*"
  - "sami2py/fortran/*"
  - "setup.py"
  - ".*"
  - "*.md"
  - "*.rst"
  - "MANIFEST.in"
  - "mypy.ini"
  - "setup.cfg"
